cronjob:
  image: "ghcr.io/gopaytech/istio-upgrade-worker"
  tag: "master"
  schedule: "32 5 * * *"
  timeZone: 'Asia/Jakarta'

resources:
  limits:
    cpu: 1024m
    memory: 1024Mi
  requests:
    cpu: 256m
    memory: 256Mi

serviceAccount:
  imagePullSecrets: []
  automountServiceAccountToken: true

podLabels: {}

configuration:
  clusterName: "my-cluster"
  rolloutIntervalSecond: 30
  maximumPercentageRolloutInSingleExecution: 20
  maximumIteration: 5
  preUpgradeNotificationSecond: 600

  enableDeploymentFreeze: true
  deploymentFreezeDates:
  - "2024-01-01"
  enableRolloutAtWeekend: false

  timeLocation: "Asia/Jakarta"
  timeFormat: "2006-01-02"

  storageMode: "configmap"
  storageConfigMapName: "istio-auto-upgrade-config"
  storageConfigMapNameSpace: "istio-system"

  notificationMode: slack
  slackWebhookSecretName: slack-webhook-secret

  istioNamespaceCanaryLabel: istio.io/rev=default
  istioNamespaceLabel: istio-injection=enabled

