apiVersion: v1
entries:
  istio-upgrade-worker:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-09-29T09:42:32.218603+07:00"
    digest: 81ce8d6f329a1828afeb92b1784f6b781cbd39aef96d8b6dad7f0c6f7d49f4c7
    home: https://github.com/gopaytech/istio-upgrade-worker
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-upgrade-worker
    type: application
    urls:
    - istio-upgrade-worker-1.0.0.tgz
    version: 1.0.0
generated: "2024-09-29T09:42:32.217991+07:00"
