apiVersion: v1
entries:
  istio-upgrade-worker:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2024-09-29T10:47:30.651282+07:00"
    digest: a34757e30ffaa1dbf3936010aef4af1cda22eadab9b9744ba82db220eacfe29e
    home: https://github.com/gopaytech/istio-upgrade-worker
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-upgrade-worker
    type: application
    urls:
    - istio-upgrade-worker-1.0.0.tgz
    version: 1.0.0
generated: "2024-09-29T10:47:30.650808+07:00"
