apiVersion: v1
entries:
  istio-upgrade-worker:
  - apiVersion: v2
    appVersion: 1.1.1
    created: "2025-07-03T09:03:25.990837+07:00"
    digest: 761fed4333c1924ffa661c0041600792ad1701b85a272a1abdde9b10a81677b0
    home: https://github.com/gopaytech/istio-upgrade-worker
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-upgrade-worker
    type: application
    urls:
    - istio-upgrade-worker-1.1.1.tgz
    version: 1.1.1
  - apiVersion: v2
    appVersion: 1.1.0
    created: "2025-07-03T09:03:25.990414+07:00"
    digest: 3ef20783cc1231f3e6ec8a4e53667ec59ad8bd838cd0c99f679bf45d8fa6c183
    home: https://github.com/gopaytech/istio-upgrade-worker
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-upgrade-worker
    type: application
    urls:
    - istio-upgrade-worker-1.1.0.tgz
    version: 1.1.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2025-07-03T09:03:25.989598+07:00"
    digest: 6385974636e6b37cb53188476bdc4585fb84ed9e1a24d431d2a4b2d8612ba7e1
    home: https://github.com/gopaytech/istio-upgrade-worker
    maintainers:
    - email: zufardhiyaulhaq@gmail.com
      name: Zufar Dhiyaulhaq
      url: https://zufardhiyaulhaq.com
    name: istio-upgrade-worker
    type: application
    urls:
    - istio-upgrade-worker-1.0.0.tgz
    version: 1.0.0
generated: "2025-07-03T09:03:25.988738+07:00"
